// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Neon pooled URLs can hit P1002 (advisory lock timeout) on `migrate`.
    // Prefer a direct (non-pooler) URL for CLI migrations only — see `.env.example`.
    url:
      process.env["MIGRATE_DATABASE_URL"] ??
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["DIRECT_URL"] ??
      process.env["DATABASE_URL"],
  },
});
