"use client"

import { useState, useEffect, useRef, useCallback } from "react"
import type { DestinationInfo } from "@/lib/gemini"
import { formatUiDateTimeLong } from "@/lib/format-time"
import { DestinationMap } from "@/components/trips/DestinationMap"
import { SpeakButton, getSpeechLang } from "@/components/shared/SpeakButton"

interface DestinationOverviewProps {
  tripId: string
  destination: string
  destinationInfo: DestinationInfo | null
  onGenerated: () => void
}

export function DestinationOverview({
  tripId,
  destination,
  destinationInfo,
  onGenerated,
}: DestinationOverviewProps) {
  const [info, setInfo] = useState<DestinationInfo | null>(destinationInfo)
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const hasAutoGenerated = useRef(false)

  const handleGenerate = useCallback(async () => {
    setIsGenerating(true)
    setError(null)
    try {
      const res = await fetch(`/api/trips/${tripId}/destination`, {
        method: "POST",
      })
      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        throw new Error(data.error || "שגיאה ביצירת מידע על היעד")
      }
      const data = await res.json()
      setInfo(data)
      onGenerated()
    } catch (err) {
      setError(err instanceof Error ? err.message : "שגיאה לא צפויה")
    } finally {
      setIsGenerating(false)
    }
  }, [tripId, onGenerated])

  useEffect(() => {
    if (!info && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true
      handleGenerate()
    }
  }, [info, handleGenerate])

  if (isGenerating) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <div className="h-10 w-10 animate-spin rounded-full border-4 border-zinc-200 border-t-blue-500" />
        <p className="mt-4 text-sm font-medium text-zinc-700 dark:text-zinc-300">
          מכין מידע על {destination}...
        </p>
        <p className="mt-1 text-xs text-zinc-400">
          זה עשוי לקחת מספר שניות
        </p>
      </div>
    )
  }

  if (error && !info) {
    return (
      <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-center dark:border-red-800 dark:bg-red-900/20">
        <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
        <button
          onClick={handleGenerate}
          className="mt-3 rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700"
        >
          נסה שוב
        </button>
      </div>
    )
  }

  if (!info) return null

  const speechLang = getSpeechLang(info.countryCode)

  const glanceCards = [
    { icon: "🏛️", label: "בירה", value: info.atAGlance.capital },
    { icon: "👥", label: "אוכלוסיה", value: info.atAGlance.population },
    { icon: "🗣️", label: "שפות", value: info.atAGlance.languages },
    { icon: "💰", label: "מטבע", value: info.atAGlance.currency },
    { icon: "💱", label: "שער חליפין", value: info.atAGlance.exchangeRate },
    { icon: "🕐", label: "אזור זמן", value: info.atAGlance.timezone },
    { icon: "🔌", label: "חשמל", value: info.atAGlance.electricPlug },
    { icon: "🚨", label: "חירום", value: info.atAGlance.emergencyNumber },
    { icon: "💵", label: "טיפים", value: info.atAGlance.tippingCustoms },
  ]

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`https://flagcdn.com/w160/${info.countryCode}.png`}
            alt={info.countryNameHebrew}
            className="h-12 rounded shadow-sm"
          />
          <div>
            <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">
              {info.destinationNameHebrew}
            </h2>
            <p className="text-sm text-zinc-500">{info.countryNameHebrew}</p>
          </div>
        </div>
        <button
          onClick={handleGenerate}
          disabled={isGenerating}
          className="flex items-center gap-1.5 rounded-lg border border-zinc-200 bg-white px-3 py-1.5 text-sm text-zinc-600 hover:bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-700"
        >
          <svg
            className="h-4 w-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
            />
          </svg>
          רענן מידע
        </button>
      </div>

      {/* At a Glance */}
      <section>
        <h3 className="mb-3 text-lg font-semibold text-zinc-900 dark:text-zinc-100">
          מבט מהיר
        </h3>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
          {glanceCards.map((card) => (
            <div
              key={card.label}
              className="rounded-xl border border-zinc-200 bg-white p-3 dark:border-zinc-700 dark:bg-zinc-800"
            >
              <div className="text-xs text-zinc-500">
                {card.icon} {card.label}
              </div>
              <div className="mt-1 text-sm font-medium text-zinc-900 dark:text-zinc-100">
                {card.value}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Good to Know */}
      <section>
        <h3 className="mb-3 text-lg font-semibold text-zinc-900 dark:text-zinc-100">
          טוב לדעת
        </h3>
        <div className="space-y-3">
          {info.goodToKnow.map((item, i) => (
            <div
              key={i}
              className="rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-700 dark:bg-zinc-800"
            >
              <h4 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
                {item.title}
              </h4>
              <p className="mt-1 text-sm leading-relaxed text-zinc-600 dark:text-zinc-400">
                {item.content}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Kids Corner */}
      <section>
        <h3 className="mb-3 text-lg font-semibold text-zinc-900 dark:text-zinc-100">
          🧒 פינת הילדים
        </h3>
        <div className="space-y-3">
          {/* Fun Facts */}
          <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-800 dark:bg-amber-900/20">
            <h4 className="text-sm font-semibold text-amber-800 dark:text-amber-300">
              עובדות מעניינות
            </h4>
            <ul className="mt-2 space-y-1.5">
              {info.kidsCorner.funFacts.map((fact, i) => (
                <li
                  key={i}
                  className="flex gap-2 text-sm text-zinc-700 dark:text-zinc-300"
                >
                  <span className="text-amber-500">✦</span>
                  {fact}
                </li>
              ))}
            </ul>
          </div>

          {/* Story */}
          <div className="rounded-xl border border-purple-200 bg-purple-50 p-4 dark:border-purple-800 dark:bg-purple-900/20">
            <h4 className="text-sm font-semibold text-purple-800 dark:text-purple-300">
              {info.kidsCorner.story.title}
            </h4>
            <p className="mt-2 text-sm leading-relaxed text-zinc-700 dark:text-zinc-300">
              {info.kidsCorner.story.content}
            </p>
          </div>
        </div>
      </section>

      {/* Map */}
      {info.coordinates && (
        <section>
          <h3 className="mb-3 text-lg font-semibold text-zinc-900 dark:text-zinc-100">
            מפה
          </h3>
          <DestinationMap
            center={info.coordinates}
            destinationName={info.destinationNameHebrew}
          />
        </section>
      )}

      {/* Tourist Dictionary */}
      <section>
        <h3 className="mb-3 text-lg font-semibold text-zinc-900 dark:text-zinc-100">
          מילון לתייר
        </h3>
        <div className="space-y-4">
          {info.dictionary.map((group, i) => (
            <div
              key={i}
              className="overflow-hidden rounded-xl border border-zinc-200 dark:border-zinc-700"
            >
              <div className="bg-zinc-100 px-4 py-2 dark:bg-zinc-800">
                <h4 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
                  {group.category}
                </h4>
              </div>
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-zinc-50 dark:bg-zinc-800/50">
                    <th className="px-4 py-2 text-right text-xs font-medium text-zinc-500">
                      עברית
                    </th>
                    <th className="px-4 py-2 text-right text-xs font-medium text-zinc-500">
                      מקומית
                    </th>
                    <th className="px-4 py-2 text-right text-xs font-medium text-zinc-500">
                      תעתיק
                    </th>
                    <th className="w-10 px-2 py-2" />
                  </tr>
                </thead>
                <tbody>
                  {group.phrases.map((phrase, j) => (
                    <tr
                      key={j}
                      className="border-b border-zinc-100 dark:border-zinc-800"
                    >
                      <td className="px-4 py-2 text-zinc-700 dark:text-zinc-300">
                        {phrase.hebrew}
                      </td>
                      <td
                        dir="ltr"
                        className="px-4 py-2 font-medium text-zinc-900 dark:text-zinc-100"
                      >
                        {phrase.local}
                      </td>
                      <td className="px-4 py-2 text-zinc-500">
                        {phrase.transliteration}
                      </td>
                      <td className="px-2 py-2 text-center">
                        <SpeakButton text={phrase.local} lang={speechLang} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ))}
        </div>
      </section>

      {/* Generated timestamp */}
      <p className="text-center text-xs text-zinc-400">
        נוצר ב-
        {formatUiDateTimeLong(info.generatedAt)}
      </p>
    </div>
  )
}
